name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ add-pipelines ]
  # pull_request:
  #   branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: execute build.ps1
        shell: pwsh
        run: ./build.ps1
      
      # publish to the PowerShell Gallery
      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v19
        with:
          # The filesystem path to the module to import into the environment.
          modulePath: ./build/modules/PoShLogging
          # The NuGet API Key for PowerShell Gallery, with permission to push this module.
          NuGetApiKey: ${{ secrets.POWERSHELLGALLERYAPIKEY }}
