name: Publish to Gallery

# Controls when the action will run. 

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: execute build.ps1
        shell: pwsh
        run: ./build.ps1

      - name: publish to PSGallery
        shell: pwsh
        run: |
          Publish-Module -Path ./build/modules/powershell-logging -NuGetApiKey ${{ secrets.POWERSHELLGALLERYAPIKEY }}
